// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace baithi15.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240621040650_table_Student")]
    partial class table_Student
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("baithi15.Models.Person", b =>
                {
                    b.Property<int>("IdNhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Age")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNhanvien");

                    b.ToTable("Cau1");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("baithi15.Models.Student", b =>
                {
                    b.HasBaseType("baithi15.Models.Person");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Msv")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cau2");
                });

            modelBuilder.Entity("baithi15.Models.Student", b =>
                {
                    b.HasOne("baithi15.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("baithi15.Models.Student", "IdNhanvien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
